version: 2
updates:
  - package-ecosystem: gomod
    directory: /restclient
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /examples/restclient
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /common
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily